[pytest]
asyncio_mode = auto
pythonpath = .
asyncio_default_fixture_loop_scope = session
testpaths = tests
python_files = test_*.py
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning
    ignore::pytest.PytestUnraisableExceptionWarning
